language: php

php:
    - 7.2
    - 7.3
    - 7.4

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

env:
    global:
        - APP_ENV=test

matrix:
    fast_finish: true

install:
    - composer install --prefer-dist --no-interaction

script:
    - ./bin/console doctrine:database:drop --force
    - ./bin/console doctrine:database:create
    - ./bin/console doctrine:schema:create
    - ./bin/console doctrine:fixtures:load --no-interaction
    - ./vendor/bin/simple-phpunit
